version: '3.8'
services:
  zookeeper:
    image: zookeeper:3.6.1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    networks:
      - kafka

  kafka-0:
    image: wurstmeister/kafka:2.12-2.4.0
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka

  kafka-1:
    image: wurstmeister/kafka:2.12-2.4.0
    ports:
      - 9093:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka

  manager:
    image: kafkamanager/kafka-manager:3.0.0.4
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
    - 9000:9000
    networks:
      - kafka

networks:
  kafka: